# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HayStack-Latest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HayStack-Latest
     pod 'SDWebImage'
     pod 'IQKeyboardManagerSwift'
     pod 'Alamofire', '~> 4.9.1’
     pod 'MBProgressHUD'
     pod 'ObjectMapper'
     pod 'GoogleMaps'
     pod 'GooglePlaces'
     pod 'GooglePlacePicker'
     pod 'Firebase/Core'
     pod 'Firebase/Messaging'
     pod 'Firebase/Crashlytics'
     pod 'Firebase/Analytics'
     pod 'Firebase/Messaging'

  target 'HayStack-LatestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HayStack-LatestUITests' do
    # Pods for testing
  end

end
